### ISSUE TITLE
Allow to import hyper-ts without es6 or lib directories

### ISSUE THREAD

**Issue by mlegenhausen** [DenisFrezzato/hyper-ts#43]
With the introduction of the `ReaderMiddleware` we need to choose between `es6` and `lib` directory for imports. As the rest of the `fp-ts` ecosystem support the import without these directories I think it is consequent to add it here too.

@DenisFrezzato do you have already something like this in the pipeline if not I can pick this up?

**Comment by DenisFrezzato** [comment]
No, I don't have anything in the pipeline on this topic, feel free to pick it up.
