### ISSUE TITLE
`bindTo` messes up the monadic index

### ISSUE THREAD

**Issue by kylegoetz** [DenisFrezzato/hyper-ts#48]
## 🐛 Bug report

`bindTo` messes up the monadic index. For example, consider a broader monadic index that takes you through `AuthenticationOpen` to `AuthorizationOpen` and then `StatusOpen` and so forth.

authentication middleware:

`declare const authenticate: Middleware<AuthenticationOpen, AuthorizationOpen, unknown, AuthenticatedUser>`

one of many authorization middlewares

`declare const userHasReadAccess: (u:AuthenticatedUser) => Middleware<AuthorizationOpen, StatusOpen, unknown, AuthorizedUser>`

```typescript
const myController = pipe(
  authenticate,
  H.ichain(userHasReadAccess),
  H.bindTo('user'), // <-- property AuthenticationOpen is missing in type StatusOpen . . .
  H.bind('query', () => H.decodeQuery(/* . . . */)),
  /* . . . */
```

`bindTo` takes `Middleware<I,I,E,A>` and returns `Middleware<I,I,E,{ ... }>` but it should take `Middleware<I,O,E,A>` because not every middleware passed into `bindTo` will have the same "in' and "out" index.

### Your environment

Which versions of hyper-ts are affected by this issue? Did this work in previous versions of hyper-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |        2.10.5    |
| hyper-ts   |       0.6.5     |
| TypeScript |    3.9.2        |

**Comment by kylegoetz** [comment]
Maybe I should have phrased this as: I think this is a bug report. Alternatively, am I misunderstanding how the monadic index is supposed to work here? If it's a bug, I can make a PR. But I want confirmation this is a bug, first. In the meantime, the fix is to avoid `bind/bindTo` and instead just do nested `pipe`s (which is what we did with `fp-ts` before `bind/bindTo` became available.

**Comment by kylegoetz** [comment]
`map` should be fixed the same way, right?

Currently, `map: (f:(a:A) => B) => (m:Middleware<R,R,E,A>) => Middleware<R,R,E,B>` so how would one map over `Middleware<I,O,E,A>` where `I !== O`?

**Comment by DenisFrezzato** [comment]
@kylegoetz  I've mentioned this is the roadmap for the next version. This is not a bug, more like a feature request for `ibind` and `ibindTo` functions. `map` probably needs to be fixed though, I'll look into that too. Thanks for the report.

**Comment by kylegoetz** [comment]
@DenisFrezzato can you clarify the difference between `bind` and `ibind` then? I never understood the `chain` and `ichain` distinction, except that one does not allow you to change the index, but the other does. Is this the only difference? And thus the only difference between `bind` and a potential `ibind` is that with `ibind` the incoming and outgoing indices can be different? (Sort of like how some w-suffix functions allow a widening of the error type?)

**Comment by kylegoetz** [comment]
Also, I'll do a PR for `map`. I've got a PR for I think adding `sendFile` so it ain't my first rodeo :)

**Comment by DenisFrezzato** [comment]
> can you clarify the difference between `bind` and `ibind` then?

It's the same difference between `chain` and `ichain` (since `bind` is just a utility around `chain`). `ichain` is the indexed version of `chain`, which additionally updates the indexes.

> honestly I only ever use `ichain` and never `chain`

You should use `chain` when the operation doesn't change the indexes.

```ts
import * as H from 'hyper-ts'
import * as M from 'hyper-ts/lib/Middleware'
import { pipe } from 'fp-ts/function'
import * as t from 'io-ts'


declare functionsendStatus(
  status: H.Status,
): M.Middleware<H.StatusOpen, H.ResponseEnded, never, void>

const ReqBody = t.type({ name: t.string })

const userHandler = pipe(
  M.decodeBody(ReqBody.decode),
  // Chain a new Middleware, same indexes.
  M.chain((user) => user.name === 'Denis' ? M.right(user) : M.left('Wrong name')),
  // Chain a new Middleware with different indexes.
  M.ichain(() => sendStatus(H.Status.NoContent)),
  M.orElse(() => sendStatus(H.Status.BadRequest))
)
```

> Also, I'll do a PR for map.

`map` is fine, we need an indexed version `imap` for that too, see https://hackage.haskell.org/package/indexed-0.1.3/docs/Data-Functor-Indexed.html or https://pursuit.purescript.org/packages/purescript-indexed-monad.

**Comment by kylegoetz** [comment]
@DenisFrezzato I'm closing this issue since it appears you've implemented this in a forthcoming version.
