### ISSUE TITLE
v0.7 Roadmap

### ISSUE THREAD

**Issue by DenisFrezzato** [DenisFrezzato/hyper-ts#50]
* **Breaking change**
  * Upgrade to `fp-ts@2.10`
  * Add `fp-ts-contrib` as a peer-dependency
* **Deprecation**
  * Deprecate `Middleware` from `index.ts`, use `Middleware` module instead.
* **New Feature**
  * `Middleware`
    * Add `apS`
    * Add `apSW`
    * Add `chainEitherK`
    * Add `chainEitherKW`
    * Add `FromIO`
    * Add `fromIO`
    * Add `fromIOK`
    * Add `chainIOK`
    * Add `chainFirstIOK`
    * Add `FromTask`
    * Add `fromTask`
    * Add `fromTaskK`
    * Add `chainTaskK`
    * Add `chainFirstTaskK`
    * Add `chainTaskEitherK`
    * Add `chainTaskEitherKW`
    * Add `chainFirstTaskEitherK`
    * Add `chainFirstTaskEitherKW`
    * Add `imap`
    * Add `ibindTo`
    * Add `ibind`
    * Add `ibindW`
    * Add `iapS`
    * Add `iapSW`
  * `ReaderMiddleware`
    * Add `gets`
    * Add `fromConnection`
    * Add `modifyConnection`
    * Add `apFirst`
    * Add `apSecond`
    * Add `apS`
    * Add `apSW`
    * Add `FromEither`
    * Add `fromEither`
    * Add `chainEitherK`
    * Add `chainEitherKW`
    * Add `chainFirst`
    * Add `chainFirstW`
    * Add `chainFirstIOK`
    * Add `FromTask`
    * Add `fromTask`
    * Add `fromTaskK`
    * Add `chainTaskK`
    * Add `chainFirstTaskK`
    * Add `chainFirstTaskEitherK`
    * Add `chainFirstTaskEitherKW`
    * Add `chainFirstReaderTaskEitherK`
    * Add `chainFirstReaderTaskEitherKW`
    * Add `fromPredicate`
    * Add `filterOrElse`
    * Add `filterOrElseW`
    * Add `imap`
    * Add `ibindTo`
    * Add `ibind`
    * Add `ibindW`
    * Add `iapS`
    * Add `iapSW`
  * `express`
    * Improve `fromRequestHandler` (https://github.com/DenisFrezzato/hyper-ts/issues/39)
* **Fix**
  * `ReaderMiddleware`
    * Add out type variable in `fromMiddleware`
    * Fix type signature of `apSW` adding widening or `R`
* **Internal**
  * Use `List` from `fp-ts-contrib`

**Comment by DenisFrezzato** [comment]
@mlegenhausen I thought you might be interested in this. Also, do you have other functions/combinators that you see missing?

**Comment by mlegenhausen** [comment]
Looks good!
